version: '3'
services:
  mysql-standalone:
    #image: arm64v8/mysql:oracle
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_DATABASE: "passengerList"
    ports:
      - "3307:3306"
  airline-reservation-mysql:
    image: airline-reservation-mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql-standalone
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5